# Generated by Django 5.0.1 on 2024-02-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Not Defined'), (1, 'Water'), (2, 'Energy')], default=0)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
