# Generated by Django 5.0.1 on 2024-02-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_collection', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(default=0)),
                ('collect_date', models.DateTimeField(auto_now_add=True)),
                ('mote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
        ),
    ]
