# Generated by Django 5.0.1 on 2024-02-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='mote',
            new_name='device',
        ),
    ]
