# Generated by Django 5.0.1 on 2024-02-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_graphs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graphs',
            new_name='Graph',
        ),
    ]
