# Generated by Django 5.0.1 on 2024-02-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_graphs_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='profile_photo',
            field=models.ImageField(default='defaults/profile_default.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='type',
            field=models.IntegerField(choices=[(0, 'Not Defined'), (1, 'All WMote Devices | 24h | Raw'), (2, 'All EMote Devices | 24h | Raw')], default=0),
        ),
    ]
