# Generated by Django 5.0.1 on 2024-02-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_extenduser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='is_advisor',
            field=models.BooleanField(default=False),
        ),
    ]
