# Generated by Django 5.0.1 on 2024-05-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_device_is_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='lattes_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.IntegerField(choices=[(0, 'Not Defined'), (1, 'Water'), (2, 'Energy'), (3, 'Gas')], default=0),
        ),
        migrations.AlterField(
            model_name='graph',
            name='type',
            field=models.IntegerField(choices=[(0, 'Not Defined'), (1, 'All WMote Devices | 24h | Raw'), (2, 'All EMote Devices | 24h | Raw'), (3, 'All GMote Devices | 24h | Raw')], default=0),
        ),
    ]
