# Generated by Django 5.0.1 on 2024-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_extenduser_email_alter_extenduser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
