# Generated by Django 5.0.1 on 2024-06-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_device_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
