# Generated by Django 5.0.1 on 2024-06-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_extenduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.IntegerField(choices=[(0, 'Not Selected'), (1, 'Liters')], default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
