# Generated by Django 5.0.1 on 2024-06-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_data_type_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.IntegerField(choices=[(0, 'Not Selected'), (1, 'Volume/L')], default=0),
        ),
    ]
