# Generated by Django 5.0.1 on 2024-06-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField(blank=True)),
                ('median', models.FloatField(blank=True)),
                ('std', models.FloatField(blank=True)),
                ('cv', models.FloatField(blank=True)),
                ('max', models.FloatField(blank=True)),
                ('min', models.FloatField(blank=True)),
                ('fq', models.FloatField(blank=True)),
                ('tq', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
        ),
    ]
