# Generated by Django 5.0.1 on 2024-06-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_processeddata_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='cv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='fq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='tq',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
