# Generated by Django 5.0.1 on 2024-07-14 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_processeddata_cv_alter_processeddata_fq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authorized', models.IntegerField(choices=[(0, 'Pending'), (1, 'Not Authorized'), (2, 'Authorized')], default=0)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
        ),
    ]
