# Generated by Django 5.0.1 on 2024-07-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_device_id'),
        ('app', '0019_alter_processeddata_cv_alter_processeddata_fq_and_more'),
    ]

    operations = [
    ]
