# Generated by Django 5.0.1 on 2024-07-14 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
