# Generated by Django 5.0.1 on 2024-07-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_devicelog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
