# Generated by Django 5.0.1 on 2026-02-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_devicelog_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='voltage',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Selected'), (127, '127V'), (220, '220V')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.IntegerField(choices=[(0, 'Not Selected'), (1, 'Volume (L)'), (2, 'kWh'), (3, 'Watt'), (4, 'Ampere')], default=0),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='interval',
            field=models.IntegerField(choices=[(0, 'Not Selected'), (1, 'Hourly')], default=0),
        ),
    ]
