# Generated by Django 5.0.1 on 2024-08-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_extenduser_email'),
        ('app', '0022_alter_devicelog_api_token_and_more'),
    ]

    operations = [
    ]
